version: '3'

services:
  flask:
    container_name: flask
    build: ./back-end
    command: ./back-end/app.py
    ports:
      - "443:443"
    volumes:
      - ./back-end:/back-end
    hostname: flask
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
      SQLALCHEMY_DATABASE_URI: mysql://admin:4pa1z&ABK78R@mysql/coincube
      EXAPI_URL: http://exapi:9000
      VAULT_SEED: 'LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlKS1FJQkFBS0NBZ0VBcCtmZHFWdmc4YWlKTmdZV1gycGdSTEZGZ1QrcFgwTU8xNVRpdEcycW12T2JTa21lCk5PRUsvcmFGbWszUHR4YitDOTRqSkVlWVlSTWxYWWtBNWdOVkNtSzF3SkRJanJRT0lCSkFxZ3pDN0pYRzd3aksKYzA1U1IzMXhKMDJGZ1NyaG5RT0cvQU56UW5MTEdOc25IVitxWUlDODgreXRmMmdrZEJkYVcwZnc1MnJGU01lbQpqZE10bjYvSmsxd0pZRysrYU9TL1ZDenJzb0M3clg5TGZKY3BhZ0FyVENOYUNKMlA2L1I5UlM3UkphY1Y3M3hvCmNPOEc4TkJRUElSUktEWmc2cHhWV282ZWhLb01BN1pSYzN6b2RmWlpycjFTeEthZHA1K1lIK0Jxdis2UGU3TUUKVnArRm5kU0FiMGVZK0JLaEFrRk94aUhJelNJT05Wd3Q4N3FjVm9ZNjJ3YnVDSERrUDgvRXNKNkY0Y0ViRHgwUQpqbkY3Y0o0VnBBOHJLeTRoS3hZMy9xN2QxMEwxYlVDbjhXUG9qM0xHZTZ6U2ZVWnA4K0hvVisxbSsxS2F4Y0VMCkROdFVvM1JBK0FJVlFYMHRPZ1ZBczA4Y2syelZXak00bUV2WkJtTlJEd2tBR2hodWd3Znp1d2dBNGhNYVhUb0wKeHh3NEEzZmtZamtNVVJLVnNnVFRCNVVXbDRlMWE0dWoxTDAxRk9uM3VYNXRzSTJQVmllcHlaQ3dlK2xINm1OTgp3OURoc2ovMjFGQm16bVUzS3MzeDQ0V05NS3RWSHVoeUZFVGI4NnNsQ2FTVlkxQ2ZKOHFTZVZ4bDFXQ3F3cmpqCmFWS0pJTFpVYmdYY2VyeDVpNVVuMTJHSkZUZFBRZUIzb3pSdnFDWGVZSUhpaWh5emI2MHNmT0pKRXhzQ0F3RUEKQVFLQ0FnQUxHOXdlaUdXcGwyejhsZ3FFNVpUWTlxR1NtNU9wS2RhaGpNZ3pCODV4MGd4RUxmcTVwT29GVUM0bQp0MTgyemQ2aENtRm8xUlBQMkdSd2U5QURaOVVJaXQ5YmpqaTJ1RkwyN0Q0N0FmMGppZ1ZQYTFWNXE0VG1GZmFXCmt4cHlJVlFyL3orL0RMdGplaFRWNENvR1YzMytSSVk3M1R6ZFlSYUlWOE15cHQvWmI4Yjl1YmZiU2syS2N5YnoKQ1BQVjNZN0xnZGJteXRJTlRWY2RjMzZiRDZVOXppVVBOSWVRYWx4TFVERzVrZzlrWGxtbExxWDZVdFl5dUpXVwphMnF6TG1YYkg5ekYwUW5MM1RST1NwRzVBbHFlODEyYm9nc0gxNzQyaU9pWHMxRmN3WHZjdzB0V0w5ZTNTWWYxCjFOYmFFdUYwTkwzeGZlcTdKN1dvOGlCWUw5Q0lEWVA2dUl0c0ZCa0dPbVJwUERpOVhRYjdyQllJQld2MGU1RDgKUDIwTUhrU1U4d2o1blBXNUVKMGpCSFh1aEVYYWJkUHU3YmR4VnJQVHpEcjJCSzVVRzdrckxkREZPMTRTOG9ULwphcEFRNlNGMzRHMXhkMkU4Z1YyOENQWEM0c1NuVDhlY1dDM1VZTHZRaUwxNDZLeUZ5bnBnbCtOcU5nYUtRTEtHCm5UdHNrZDNiSWEvOGxmSEJ5czFLVUtnNHlrT0RFblVDZlZWMCtHWVdIUHpqS21FM3R5ZEdpMFMrNitNR2xHZkcKczdkRVdQcG5TUUJqSU1KWFA3cU05YnFPSkoyemczbysvS1pSM2txMU5EQUNWVHhSZzVnVFk3NkRxNkVGcUt4eQoyVXhxWjk0VFlnclNSUlJzYVA3Um5WVThIUlVhZ3hYMmQ3VFE0K2dPSldUK29YTFBnUUtDQVFFQXhyUlVyVHRRCmg4eDR1eW4wbmxNVkhmVVJ3dm1MM0N1TkljbW4xUmQ1RDl6RHljUXFTbXFkWVRBUFpBVFM3WTlycS9WcVkzalQKYlFYZVdnaDA1LzlnbG1yWldOcmFBTmtCc09qZXh3cjd1QTVCb0RHbE5EY2kxUVh0S2pLVERYVVhHSzJaejQ3QQprSFBhMUNibHk3d2doUE9JSXc3VXdZNk1tVHZ0YzlYbGNnYy90bW1ua1hQNWxSbXhmK3U5UDUwWVN3UmV6K08rCmV0ck5xMW9uTkJoTDdJdTVWWnBiZSszWWJndjEwdVZLaUlHdHJTd0IrM3BFZ0tDMVZHbzhVemZLckU1MHorU3EKU1YvenpqQThVSmVubG8wN1VreVZ3WUJtM0RRUktEeG53dTVoUUV5bEhXeHBsT2oySmFzK0FNK2N6RGQ0azkySgpQTHBIVE04UHZ3WjdMUUtDQVFFQTJGSVZNcHJVUjBHdFg0eFp1RW5aaFp1T3BZK3V4eVRMYk53T0pxS1oxWHprCmZNQ0xUZEZWMk9jbzNmK0UwNXhKV0dPdUFEeHZZL01OQm9mbTBpTVNITFBFVWNGK3AwYlV2VFVJUUwwVUd2R1IKVU9nMmNMTWszZzN0SE1GT2JEdXFFZ1h1SnVUTTNQeDRzM0lNbTF1RXJ6UlpOUHJ1OW53YXo3dmNzak1CL0lRNwppeWhMMDQ1U2xES1JqQXFwdzdkUlNYUjZxVml3RXY4L2tPcU1OS2tSUTZTMkdWQ1ArRU1PU0JpQVNwMWc1VWpXCnF5NzNNdGZocDByT282VmZFK1RjYU1WdW8wRlhkUWRES2wwaFYzVDd1bTlORkVyUkZCQTFCMWhjaHNMT3RRY3gKNGJjTGlwREdQS2k5VUpmaHdqSUVRUkFraG1MMStBR0owMjAvYWdZVVp3S0NBUUVBak9zcStrZ01qcUpXSlBaVwpRMHBNdVpncDVvcXZ3NDhuWWdUdmY5Skx5eElYMENuTWpFWWNJdWJBbzRCQVRyWGQrRy90NldteEY2cUh6SFllCjRzRmNNSkRLWDVlbDc5LzJzUTRWb0RlTDJUWlRHRmJkQUxEeGhQM1UrbzR2ZCtYSVlYb01rUVIrVUhPNWg2ZW0KWk55Z2UybHk3Tm9Cek50Wm52cS9KZDFXQVk1ZWd2RmZJMnFLWUZGK2JtZ3pLTUF5a0ZFakpIQXhrRk5JZFBOVQp4ajlNNlE4V2V6MGpFRHJYdVFQR2JMQ3NNUzgyaW8raFFFV3YrMEQrR0VYWFRuVk15UEpES1lUVHQ0SFRHREZoCk5RNjRqYTdQbVVnekZLNEpSTFd3VFVhNWw2Y1RWVlNGN040TDZzMWtjOGFFREhNd2tpdnMyWUROYVVINmV1Q0cKSEVWdWFRS0NBUUF3T2lTVnNxVU8rZHFBU2RjYTJnUVA0SDF0OWRtZWRscVArNE9BSTVJdVlYakRRMTRMVEZkYQpVemJ1UDNCS2lUWms2Vnc2bXo2dVJ0cXBrUlRwMW4zTVBsdlBhbGNsVGdwUjRJZmxmd0lEZThYTkJ1aFVPZXhIClFVMlNzcG9jVVRUNmJhNEpwOHJ3bmF6L1BMY0l6OStGL0NMRFNBcU1rMkNhM2FRM2FsM1FBVjhSQ0R2WGY0eHoKazg2VkxTOXAvZTIyZGF4L0l0R21lcGVlWkZ3N3hWR2ZCaEsvRkJIMDVHWkR0b3FybCtpcFZaTGVlVXNOWDhuawpOUzVhbDV6WjM1VXdHb3d2QTN0UEVQNXRiSFBwZnFBOGtXSGEyMDgvck5sVnVPSnYvUEIrdFlydWFwTzlJY2ZBCmNGSThySS9kYnE4NkhqSTJiOHVzcmhNZk91VC9hem1UQW9JQkFRQ0U1TGxTVkRCTWVOc0ZseXJ6bmlIZkFqb1cKMXVxRmdWUmNncGVFelJ3L3RVV1ZMeXJMRHlqUHBCa01CTDZBMUFHaVkvaTZVeU9aWUtYVHVXMHdlTm1vSG5yUApTeW5QbVFBU0EvN29RK09DNU1RbVZCZm52bEFKWXdPVWhsbXd0R3gxRitwSW5FOVNYeHA1QjNYNmtrQnBKY3lHCkRqQ3RjV2hIS1B4bko4Yzkzd1JKelNXQXgrMlJ6cW4rRklhNFdDN2M1WkJ4dUdOOGd5SDJIVVREWGRWU0ZEYTgKTkZPUitaV3hjZTFsYVcwY2wwbUI1NGRsczE5M0RBQ1diR1BTaDF4aTdYNDV0V0hBNXlhdFBtanhFSWJTRWlYRQpJM1YyMnlSSW5NcFZibGFUQ3V3TTJQNEk1REQrK3RPaCtnNW1pUU5tbXdiTkQwQkhMQjhhU0xJUmtRbmkKLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0='
      FLASK_DEBUG: 1
      PORT: 443
      HOST: '0.0.0.0'
    networks:
      - back

  exapi:
    build: ./exapi
    environment:
      PORT: 9000
      PYTHONUNBUFFERED: 1
    ports:
      - "9000:9000"
    restart: always
    networks:
      - back

  celery_cron_job:
    build: ./cron-job
    volumes:
      - .:/code
    environment:
      PYTHONUNBUFFERED: 1
      COMPOSE_HTTP_TIMEOUT: 300
      SQLALCHEMY_DATABASE_URI: mysql://admin:4pa1z&ABK78R@mysql/coincube
      CELERY_BROKER_URL: redis://redis-cron:6379
      EXAPI_URL: http://exapi:9000
      CMC_API_KEY: ''
      CMC_LIMIT: 500
    command: >
      /opt/conda/bin/celery worker
      --app celery_update
      --hostname %h-%n
      --loglevel DEBUG
      --concurrency 10
    depends_on:
      - redis-cron
      - exapi
      - mysql
    networks:
      - redis-cron-net
      - back

  celery_scheduler:
    build: ./cron-job
    volumes:
      - .:/code
    environment:
      PYTHONUNBUFFERED: 1
      COMPOSE_HTTP_TIMEOUT: 300
      SQLALCHEMY_DATABASE_URI: mysql://admin:4pa1z&ABK78R@mysql/coincube
      CELERY_BROKER_URL: redis://redis-cron:6379
      EXAPI_URL: http://exapi:9000
      CMC_API_KEY: ''
      CMC_LIMIT: 500
    command: >
      /opt/conda/bin/celery
      -A celery_update beat
      --loglevel DEBUG
    depends_on:
      - redis-cron
      - exapi
      - mysql
    networks:
      - redis-cron-net
      - back

  trader_scheduler:
    build: ./trade-engine
    environment:
      PYTHONUNBUFFERED: 1
      COMPOSE_HTTP_TIMEOUT: 300
      SQLALCHEMY_DATABASE_URI: mysql://admin:4pa1z&ABK78R@mysql/coincube
      CELERY_BROKER_URL: redis://redis:6379
      EXAPI_URL: http://exapi:9000
    command: >
      /opt/conda/bin/celery
      -A celery_update beat
      --loglevel DEBUG
    depends_on:
      - redis
      - exapi
    networks:
      - redis-net
      - back

  trader:
    build: ./trade-engine
    environment:
      PYTHONUNBUFFERED: 1
      COMPOSE_HTTP_TIMEOUT: 300
      SQLALCHEMY_DATABASE_URI: mysql://admin:4pa1z&ABK78R@mysql/coincube
      CELERY_BROKER_URL: redis://redis:6379
      EXAPI_URL: http://exapi:9000
      VAULT_SEED: 'LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlKS1FJQkFBS0NBZ0VBcCtmZHFWdmc4YWlKTmdZV1gycGdSTEZGZ1QrcFgwTU8xNVRpdEcycW12T2JTa21lCk5PRUsvcmFGbWszUHR4YitDOTRqSkVlWVlSTWxYWWtBNWdOVkNtSzF3SkRJanJRT0lCSkFxZ3pDN0pYRzd3aksKYzA1U1IzMXhKMDJGZ1NyaG5RT0cvQU56UW5MTEdOc25IVitxWUlDODgreXRmMmdrZEJkYVcwZnc1MnJGU01lbQpqZE10bjYvSmsxd0pZRysrYU9TL1ZDenJzb0M3clg5TGZKY3BhZ0FyVENOYUNKMlA2L1I5UlM3UkphY1Y3M3hvCmNPOEc4TkJRUElSUktEWmc2cHhWV282ZWhLb01BN1pSYzN6b2RmWlpycjFTeEthZHA1K1lIK0Jxdis2UGU3TUUKVnArRm5kU0FiMGVZK0JLaEFrRk94aUhJelNJT05Wd3Q4N3FjVm9ZNjJ3YnVDSERrUDgvRXNKNkY0Y0ViRHgwUQpqbkY3Y0o0VnBBOHJLeTRoS3hZMy9xN2QxMEwxYlVDbjhXUG9qM0xHZTZ6U2ZVWnA4K0hvVisxbSsxS2F4Y0VMCkROdFVvM1JBK0FJVlFYMHRPZ1ZBczA4Y2syelZXak00bUV2WkJtTlJEd2tBR2hodWd3Znp1d2dBNGhNYVhUb0wKeHh3NEEzZmtZamtNVVJLVnNnVFRCNVVXbDRlMWE0dWoxTDAxRk9uM3VYNXRzSTJQVmllcHlaQ3dlK2xINm1OTgp3OURoc2ovMjFGQm16bVUzS3MzeDQ0V05NS3RWSHVoeUZFVGI4NnNsQ2FTVlkxQ2ZKOHFTZVZ4bDFXQ3F3cmpqCmFWS0pJTFpVYmdYY2VyeDVpNVVuMTJHSkZUZFBRZUIzb3pSdnFDWGVZSUhpaWh5emI2MHNmT0pKRXhzQ0F3RUEKQVFLQ0FnQUxHOXdlaUdXcGwyejhsZ3FFNVpUWTlxR1NtNU9wS2RhaGpNZ3pCODV4MGd4RUxmcTVwT29GVUM0bQp0MTgyemQ2aENtRm8xUlBQMkdSd2U5QURaOVVJaXQ5YmpqaTJ1RkwyN0Q0N0FmMGppZ1ZQYTFWNXE0VG1GZmFXCmt4cHlJVlFyL3orL0RMdGplaFRWNENvR1YzMytSSVk3M1R6ZFlSYUlWOE15cHQvWmI4Yjl1YmZiU2syS2N5YnoKQ1BQVjNZN0xnZGJteXRJTlRWY2RjMzZiRDZVOXppVVBOSWVRYWx4TFVERzVrZzlrWGxtbExxWDZVdFl5dUpXVwphMnF6TG1YYkg5ekYwUW5MM1RST1NwRzVBbHFlODEyYm9nc0gxNzQyaU9pWHMxRmN3WHZjdzB0V0w5ZTNTWWYxCjFOYmFFdUYwTkwzeGZlcTdKN1dvOGlCWUw5Q0lEWVA2dUl0c0ZCa0dPbVJwUERpOVhRYjdyQllJQld2MGU1RDgKUDIwTUhrU1U4d2o1blBXNUVKMGpCSFh1aEVYYWJkUHU3YmR4VnJQVHpEcjJCSzVVRzdrckxkREZPMTRTOG9ULwphcEFRNlNGMzRHMXhkMkU4Z1YyOENQWEM0c1NuVDhlY1dDM1VZTHZRaUwxNDZLeUZ5bnBnbCtOcU5nYUtRTEtHCm5UdHNrZDNiSWEvOGxmSEJ5czFLVUtnNHlrT0RFblVDZlZWMCtHWVdIUHpqS21FM3R5ZEdpMFMrNitNR2xHZkcKczdkRVdQcG5TUUJqSU1KWFA3cU05YnFPSkoyemczbysvS1pSM2txMU5EQUNWVHhSZzVnVFk3NkRxNkVGcUt4eQoyVXhxWjk0VFlnclNSUlJzYVA3Um5WVThIUlVhZ3hYMmQ3VFE0K2dPSldUK29YTFBnUUtDQVFFQXhyUlVyVHRRCmg4eDR1eW4wbmxNVkhmVVJ3dm1MM0N1TkljbW4xUmQ1RDl6RHljUXFTbXFkWVRBUFpBVFM3WTlycS9WcVkzalQKYlFYZVdnaDA1LzlnbG1yWldOcmFBTmtCc09qZXh3cjd1QTVCb0RHbE5EY2kxUVh0S2pLVERYVVhHSzJaejQ3QQprSFBhMUNibHk3d2doUE9JSXc3VXdZNk1tVHZ0YzlYbGNnYy90bW1ua1hQNWxSbXhmK3U5UDUwWVN3UmV6K08rCmV0ck5xMW9uTkJoTDdJdTVWWnBiZSszWWJndjEwdVZLaUlHdHJTd0IrM3BFZ0tDMVZHbzhVemZLckU1MHorU3EKU1YvenpqQThVSmVubG8wN1VreVZ3WUJtM0RRUktEeG53dTVoUUV5bEhXeHBsT2oySmFzK0FNK2N6RGQ0azkySgpQTHBIVE04UHZ3WjdMUUtDQVFFQTJGSVZNcHJVUjBHdFg0eFp1RW5aaFp1T3BZK3V4eVRMYk53T0pxS1oxWHprCmZNQ0xUZEZWMk9jbzNmK0UwNXhKV0dPdUFEeHZZL01OQm9mbTBpTVNITFBFVWNGK3AwYlV2VFVJUUwwVUd2R1IKVU9nMmNMTWszZzN0SE1GT2JEdXFFZ1h1SnVUTTNQeDRzM0lNbTF1RXJ6UlpOUHJ1OW53YXo3dmNzak1CL0lRNwppeWhMMDQ1U2xES1JqQXFwdzdkUlNYUjZxVml3RXY4L2tPcU1OS2tSUTZTMkdWQ1ArRU1PU0JpQVNwMWc1VWpXCnF5NzNNdGZocDByT282VmZFK1RjYU1WdW8wRlhkUWRES2wwaFYzVDd1bTlORkVyUkZCQTFCMWhjaHNMT3RRY3gKNGJjTGlwREdQS2k5VUpmaHdqSUVRUkFraG1MMStBR0owMjAvYWdZVVp3S0NBUUVBak9zcStrZ01qcUpXSlBaVwpRMHBNdVpncDVvcXZ3NDhuWWdUdmY5Skx5eElYMENuTWpFWWNJdWJBbzRCQVRyWGQrRy90NldteEY2cUh6SFllCjRzRmNNSkRLWDVlbDc5LzJzUTRWb0RlTDJUWlRHRmJkQUxEeGhQM1UrbzR2ZCtYSVlYb01rUVIrVUhPNWg2ZW0KWk55Z2UybHk3Tm9Cek50Wm52cS9KZDFXQVk1ZWd2RmZJMnFLWUZGK2JtZ3pLTUF5a0ZFakpIQXhrRk5JZFBOVQp4ajlNNlE4V2V6MGpFRHJYdVFQR2JMQ3NNUzgyaW8raFFFV3YrMEQrR0VYWFRuVk15UEpES1lUVHQ0SFRHREZoCk5RNjRqYTdQbVVnekZLNEpSTFd3VFVhNWw2Y1RWVlNGN040TDZzMWtjOGFFREhNd2tpdnMyWUROYVVINmV1Q0cKSEVWdWFRS0NBUUF3T2lTVnNxVU8rZHFBU2RjYTJnUVA0SDF0OWRtZWRscVArNE9BSTVJdVlYakRRMTRMVEZkYQpVemJ1UDNCS2lUWms2Vnc2bXo2dVJ0cXBrUlRwMW4zTVBsdlBhbGNsVGdwUjRJZmxmd0lEZThYTkJ1aFVPZXhIClFVMlNzcG9jVVRUNmJhNEpwOHJ3bmF6L1BMY0l6OStGL0NMRFNBcU1rMkNhM2FRM2FsM1FBVjhSQ0R2WGY0eHoKazg2VkxTOXAvZTIyZGF4L0l0R21lcGVlWkZ3N3hWR2ZCaEsvRkJIMDVHWkR0b3FybCtpcFZaTGVlVXNOWDhuawpOUzVhbDV6WjM1VXdHb3d2QTN0UEVQNXRiSFBwZnFBOGtXSGEyMDgvck5sVnVPSnYvUEIrdFlydWFwTzlJY2ZBCmNGSThySS9kYnE4NkhqSTJiOHVzcmhNZk91VC9hem1UQW9JQkFRQ0U1TGxTVkRCTWVOc0ZseXJ6bmlIZkFqb1cKMXVxRmdWUmNncGVFelJ3L3RVV1ZMeXJMRHlqUHBCa01CTDZBMUFHaVkvaTZVeU9aWUtYVHVXMHdlTm1vSG5yUApTeW5QbVFBU0EvN29RK09DNU1RbVZCZm52bEFKWXdPVWhsbXd0R3gxRitwSW5FOVNYeHA1QjNYNmtrQnBKY3lHCkRqQ3RjV2hIS1B4bko4Yzkzd1JKelNXQXgrMlJ6cW4rRklhNFdDN2M1WkJ4dUdOOGd5SDJIVVREWGRWU0ZEYTgKTkZPUitaV3hjZTFsYVcwY2wwbUI1NGRsczE5M0RBQ1diR1BTaDF4aTdYNDV0V0hBNXlhdFBtanhFSWJTRWlYRQpJM1YyMnlSSW5NcFZibGFUQ3V3TTJQNEk1REQrK3RPaCtnNW1pUU5tbXdiTkQwQkhMQjhhU0xJUmtRbmkKLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0='
    command: >
      /opt/conda/bin/celery worker
      --app celery_update
      --hostname %h-%n
      --loglevel DEBUG
      --concurrency 5
    depends_on:
      - redis
      - exapi
    networks:
      - redis-net
      - back

  mysql:
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: 4pa1z&ABK78R
      MYSQL_ROOT_PASSWORD: 4pa1z&ABK78R
      MYSQL_DATABASE: coincube
    restart: always
    networks:
      - back

  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    expose:
      - 6379
    networks:
      - redis-net
    volumes:
      - redis-data:/data

  redis-cron:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis-cron
    expose:
      - 6379
    networks:
      - redis-cron-net
    volumes:
      - redis-cron-data:/data

volumes:
  mysql-data:
    driver: local
  redis-data:
  redis-cron-data:

networks:
  back:
    driver: bridge
  redis-net:
  redis-cron-net: